# Generated by Django 5.2.11 on 2026-02-18 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campana', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCampana',
            fields=[
                ('id_ledcam', models.AutoField(primary_key=True, serialize=False)),
                ('abrio_email', models.BooleanField(default=False)),
                ('click', models.BooleanField(default=False)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campana.campana')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
