# Generated by Django 5.2.11 on 2026-04-03 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='id_cat',
        ),
        migrations.AddField(
            model_name='catalogo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='categoria',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('niño', 'Niño')], max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo/'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='tipo_prenda',
            field=models.CharField(choices=[('playera', 'Playera'), ('pantalon', 'Pantalón'), ('sudadera', 'Sudadera')], max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
