# Generated by Django 5.2.11 on 2026-02-17 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id_cam', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('publico_obj', models.TextField()),
                ('mensaje', models.TextField()),
                ('estado', models.TextField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
