# Generated by Django 5.2.11 on 2026-03-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='estado',
            field=models.TextField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')]),
        ),
        migrations.AlterField(
            model_name='campana',
            name='publico_obj',
            field=models.TextField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Niño', 'Niño')]),
        ),
    ]
