# Generated by Django 5.2.11 on 2026-02-17 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_fav', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
