# Generated by Django 5.2.11 on 2026-02-17 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id_lead', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('ap', models.TextField()),
                ('am', models.TextField()),
                ('num_cel', models.TextField()),
                ('correo', models.TextField()),
                ('origen', models.TextField()),
                ('tipo_lead', models.TextField()),
                ('categoria_fav', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
